Repository SofaDefrost/plugin.SofaPython3, pull requests merged in 2019-10, with the labels that each got.

#107 New SofaPrefab decorator
  splib/__init__.py
Labels: status: to review

#108 FIX: Compilation with Windows/Visual Studio 2019
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataContainer.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/binding_controller_doc.h
  bindings/Sofa/tests/Core/BaseData.py
  src/SofaPython3/DataHelper.h
  src/SofaPython3/PythonEnvironment.cpp
  src/SofaPython3/PythonEnvironment.h
  src/SofaPython3/PythonFactory.h
  src/SofaPython3/config.h
Labels: enhancement, pr: fix, status: to review

#117 Force static variables from the python factory to be in a single compilation unit.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataContainer.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataString.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataVectorString.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Types/Binding_BoundingBox.cpp
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
  bindings/SofaTypes/CMakeLists.txt
  src/SofaPython3/PythonFactory.cpp
  src/SofaPython3/PythonFactory.h
Labels: status: to review

#124 [PythonModule_SofaGui,PythonModule_SofaTypes] Fix missing dependencies in Gui and SofaTypes CMakeLists
  CMake/SofaPython3Tools.cmake
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaTypes/CMakeLists.txt
Labels: bug (minor), status: to review

#127 Just add some example in SofaPython3
  examples/ControllerScene.py
  examples/ReadTheDocs_Example.py
Labels: status: ready
