Repository SofaDefrost/plugin.SofaPython3, pull requests merged in 2019-07, with the labels that each got.

#35 REFACTOR: Sofa modules
  CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
  bindings/Sofa/package/__init__.py
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Module_Sofa.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Types/Submodule_Types.cpp
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/Core/AutoDiffForceField.py
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Helper/Message.py
  bindings/Sofa/tests/Simulation/Node.py
  bindings/Sofa/tests/Types/BoundingBox.py
  bindings/SofaExporter/CMakeLists.txt
  bindings/SofaExporter/tests/CMakeLists.txt
  bindings/SofaExporter/tests/PythonModule_SofaExporter_test.cpp
  bindings/SofaExporter/tests/STLExporter.py
  bindings/SofaExporter/tests/tests/STLExporter.py
  bindings/SofaRuntime/CMakeLists.txt
  bindings/SofaRuntime/tests/CMakeLists.txt
  src/SofaPython3/DataHelper.h
  src/SofaPython3/config.h
Labels: refactoring, status: to review

#37 FIX: most tests
  bindings/Sofa/package/PyTypes/RGBAColor.py
  bindings/Sofa/package/PyTypes/Vec3.py
  bindings/Sofa/package/PyTypes/__init__.py
  bindings/Sofa/package/__init__.py
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataContainer.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Types/Binding_BoundingBox.cpp
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Core/Controller.py
  bindings/Sofa/tests/Core/PythonRestShapeForceField.py
  bindings/Sofa/tests/Helper/Message.py
  bindings/Sofa/tests/Simulation/Node.py
  bindings/Sofa/tests/Types/RGBAColor.py
  bindings/Sofa/tests/Types/Vec3.py
  bindings/SofaExporter/tests/tests/STLExporter.py
  src/SofaPython3/DataHelper.cpp
  src/SofaPython3/DataHelper.h
Labels: pr: fix, refactoring, status: to review

#45 REFACTOR: test suites parsing & execution
  bindings/Sofa/tests/Components/Components.py
  bindings/Sofa/tests/Core/Base.py
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Core/BaseObject.py
  bindings/Sofa/tests/Core/Controller.py
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/Core/PythonRestShapeForceField.py
  bindings/Sofa/tests/Helper/Message.py
  bindings/Sofa/tests/Simulation/Node.py
  bindings/Sofa/tests/Types/BoundingBox.py
  bindings/Sofa/tests/Types/RGBAColor.py
  bindings/Sofa/tests/Types/Vec3.py
  bindings/SofaExporter/tests/tests/STLExporter.py
  bindings/SofaRuntime/tests/tests/Base.py
  bindings/SofaTypes/tests/pyfiles/vector_test.py
  src/SofaPython3/PythonTest.cpp
Labels: refactoring, status: to review

#48 Add tests for data container dimensions, sizes, lengths shapes & values
  bindings/Sofa/tests/Core/BaseData.py
Labels: location: tests, status: to review

#50 FIX: running of individual tests
  src/SofaPython3/PythonTest.cpp
Labels: pr: fix, status: to review

#55 ADD: hasChanged / isSet methods on BaseData
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
Labels: pr: fast-merge, status: to review

#58 More robust implementation & better tests for deriveTypeFromParent
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/tests/Core/Base.py
Labels: pr: fix, status: to review

#61 [SofaPython3] Fix the Sofa.Components mecanisme that is broken.
  bindings/Sofa/src/SofaPython3/Sofa/Components/Submodule_Components.cpp
  bindings/Sofa/tests/Components/Components.py
Labels: pr: fast-merge, status: to review

#67 CLEAN Binding_Base
  CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataDict.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataDict.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataDict_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataDict.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/Binding_DataDict.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Data/binding_datadict_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  src/SofaPython3/DataFactory.cpp
  src/SofaPython3/DataFactory.h
  src/SofaPython3/DataHelper.cpp
  src/SofaPython3/DataHelper.h
Labels: status: to review

#66 FIX: convertToPython for vector<string> & fix BaseData container tests
  bindings/Sofa/tests/Core/BaseData.py
  src/SofaPython3/DataHelper.cpp
Labels: status: to review

#70 Refactor controller & Event factory
  CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseController.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseController.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/PythonScriptEvent.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/PythonScriptEvent.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  src/SofaPython3/EventFactory.cpp
  src/SofaPython3/EventFactory.h
Labels: status: to review

#71 FIX: compile error with the getLinkPath docstring
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: fast-merge, pr: fix, status: ready

#72 CLEAN: Dumb-simple refactoring to start the week
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: clean, status: to review
